CREATE TABLE if not exists ADVERTS(
TITLE varchar(255),
LINK varchar(200),
PRICE DOUBLE,
DESCRIPTION TEXT,
COUNTRY varchar(300),
CITY varchar(300),
STREETS varchar(200),
AREA DOUBLE,
PRICEPERMETER DOUBLE,
COORDINATES varchar(255)
);